server:
  port: 8099
   
eureka:
  client: 
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
zuul:
  host:
    connect-timeout-millis: 100000
    socket-timeout-millis: 100000
  routes:
    uaa: 
      path: /uaa/**
      sensitive-headers:
      service-id: AUTH-SERVER           
    micorservicio1:
      path: /micro1/**
      sensitive-headers:
      url: Microservicio1   
    micorservicio2:
      path: /micro2/**
      sensitive-headers:
      url: Microservicio2   
    micorservicio3:
      path: /micro3/**
      sensitive-headers:        
      url: Microservicio3    